### ISSUE TITLE
can u please help 

### ISSUE THREAD

**Issue by Z7l6h** [0xInfection/TIDoS-Framework#100]
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 37, in <module>
    from core.Vulnlysis.vuln import *
  File "/opt/tidos/core/Vulnlysis/vuln.py", line 17, in <module>
    from core.Vulnlysis.Oth_Bugs.othbugs import *
  File "/opt/tidos/core/Vulnlysis/Oth_Bugs/othbugs.py", line 25, in <module>
    from xmppbrute import *
  File "modules/0x03-Vulnerability+Analysis/0x03-OtherWebBugs/xmppbrute.py", line 18, in <module>
    from xmpp import Client
ImportError: No module named xmpp

**Comment by Z7l6h** [comment]
~$ pip install xmpp
Collecting xmpp
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/xmpp/

**Comment by VainlyStrain** [comment]
Hey! The xmpp dependency installation is indeed very broken. If you use TIDoS < 2.0, make sure to use the Python2 pip. If you're on Debian, you can also do `apt install python2-xmpp` (provided they didn't retire the package by now). Also, you could upgrade to TIDoS 2.0. Since I didn't find a Python 3 version of xmpp yet, the module is disabled for now, and installation should pass.

Greetings!
