### ISSUE TITLE
Tidos don't work

### ISSUE THREAD

**Issue by tXambe** [0xInfection/TIDoS-Framework#106]
Hello,

After install ( in Kali 2020.2) requirements and install tidos, when I execute tidos I have this error:

```
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 37, in <module>
    from core.Vulnlysis.vuln import *
  File "/opt/tidos/core/Vulnlysis/vuln.py", line 17, in <module>
    from core.Vulnlysis.Oth_Bugs.othbugs import *
  File "/opt/tidos/core/Vulnlysis/Oth_Bugs/othbugs.py", line 25, in <module>
    from xmppbrute import *
  File "modules/0x03-Vulnerability+Analysis/0x03-OtherWebBugs/xmppbrute.py", line 18, in <module>
    from xmpp import Client
ImportError: No module named xmpp

```
¿ Can anyone help me ?

Thanks

**Comment by sushantdhopat19** [comment]
this give error because there is not install xmpp module so first install it :)
run this command:-
sudo apt-get install libncurses5 libxml2 nmap tcpdump libexiv2-dev build-essential python-pip python-xmpp

**Comment by tXambe** [comment]
Hello,

Go to install this 

Thanks

**Comment by VainlyStrain** [comment]
Hi! Did you also install the Python requirements (`pip install -r requirements.txt`)?
Greetings!
