### ISSUE TITLE
DNSLib doesent work at all

### ISSUE THREAD

**Issue by Cezar0organisation** [0xInfection/TIDoS-Framework#110]
C:\home\fsociety\Desktop\Posao\Skripte\TIDoS-Framework> sudo python2 tidos.py
Traceback (most recent call last):
  File "tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/home/fsociety/Desktop/Posao/Skripte/TIDoS-Framework/core/tidos_main.py", line 37, in <module>
    from core.Vulnlysis.vuln import *
  File "/home/fsociety/Desktop/Posao/Skripte/TIDoS-Framework/core/Vulnlysis/vuln.py", line 16, in <module>
    from core.Vulnlysis.Misc_Bugs.webbugs import *
  File "/home/fsociety/Desktop/Posao/Skripte/TIDoS-Framework/core/Vulnlysis/Misc_Bugs/webbugs.py", line 29, in <module>
    from mailspoof import *
  File "modules/0x03-Vulnerability+Analysis/0x02-MisconfigurationBugs/mailspoof.py", line 15, in <module>
    import emailprotectionslib.dmarc as dmarclib
  File "/usr/local/lib/python2.7/dist-packages/emailprotectionslib/dmarc.py", line 3, in <module>
    import Resolver
  File "/usr/local/lib/python2.7/dist-packages/emailprotectionslib/Resolver.py", line 1, in <module>
    import dnslib
ImportError: No module named dnslib

**Comment by VainlyStrain** [comment]
Hi!

I had this issue too (and I don't know what's causing it). However, I was able to solve it by putting it in the lib/ folder of the framework, and updating the import paths. The issue should be resolved in TIDoS 2.0.

Cheers
