### ISSUE TITLE
ImportError: No module named mechanize

### ISSUE THREAD

**Issue by jepunband** [0xInfection/TIDoS-Framework#111]
hi have already installed with all of these options .. but still giving out this error..

   pip install mechanize
   pip3 install mechanize
   pip2 install mechanize
   python -m pip install mechanize

   Requirement already satisfied: mechanize in /home/dark/.local/lib/python2.7/site-packages (0.4.5)
   Requirement already satisfied: html5lib>=0.999999999 in /usr/lib/python2.7/dist-packages (from mechanize) (1.0.1)

$sudo python tidos.py -h
Traceback (most recent call last):
  File "tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/home/dark/gh/TIDoS-Framework/core/tidos_main.py", line 35, in <module>
    from core.Footprinting.footprint import *
  File "/home/dark/gh/TIDoS-Framework/core/Footprinting/footprint.py", line 19, in <module>
    from core.Footprinting.Active_Recon.activeo import *
  File "/home/dark/gh/TIDoS-Framework/core/Footprinting/Active_Recon/activeo.py", line 32, in <module>
    from cms import *
  File "modules/0x01-OSINT+Footprinting/0x02-ActiveReconnaissance/cms.py", line 13, in <module>
    import mechanize
ImportError: No module named mechanize

**Comment by VainlyStrain** [comment]
Hi! This may be because you installed the dependencies as your local user (dark), and you are running the tool as root. Root has no access per default to your .local lib, so I guess appending your python library path to the global $PATH variable would solve the issue. Alternatively, you can install the dependencies as the root user, but be aware of the security risks in doing so.

Cheers!
