### ISSUE TITLE
ImportError: No module named PIL.ExifTags

### ISSUE THREAD

**Issue by shanow7** [0xInfection/TIDoS-Framework#116]
tidos-framework# tidos
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 32, in <module>
    from core.Auxillaries.auxil import *
  File "/opt/tidos/core/Auxillaries/auxil.py", line 23, in <module>
    from imgext import *
  File "modules/0x05-Auxillaries+PF6/imgext.py", line 14, in <module>
    import PIL.ExifTags
ImportError: No module named PIL.ExifTags

**Comment by VainlyStrain** [comment]
Hi! This seems to be TIDoS 1.7, so please verify that you use python2 for both installing the dependencies and run the tool. If the error persists: some Pillow versions have had this issue. So, installing a different version of pillow may fix it.

Greetings!
