### ISSUE TITLE
Ascii Error

### ISSUE THREAD

**Issue by pc123177** [0xInfection/TIDoS-Framework#119]
when I try run I receive this error:

Traceback (most recent call last):
  File "tidconsole.py", line 779, in <module>
    main()
  File "tidconsole.py", line 771, in main
    prnt.banner()
  File "/tidos-framework/core/methods/print.py", line 412, in banner
    print(random.choice(bannerlist))
UnicodeEncodeError: 'ascii' codec can't encode character '\xb0' in position 455: ordinal not in range(128)

**Comment by VainlyStrain** [comment]
Issue should be resolved now. One of the banners had a leftover UTF8 character, which is in an invalid range for ascii. Thanks for reporting!
