### ISSUE TITLE
pls help me:  'Thread' object has no attribute 'isAlive'

### ISSUE THREAD

**Issue by phanthuthao** [0xInfection/TIDoS-Framework#121]
Traceback (most recent call last):
  File "/opt/TIDoS/tidconsole.py", line 779, in <module>
    main()
  File "/opt/TIDoS/tidconsole.py", line 770, in main
    prnt.loadstyle()
  File "/opt/TIDoS/core/methods/print.py", line 64, in loadstyle
    while thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'

**Comment by SuperPower009** [comment]
Comment puis-je corriger cette erreur cordialement 
Traceback (most recent call last):
  File "/root/tidos-framework/tidconsole.py", line 779, in <module>
    main()
  File "/root/tidos-framework/tidconsole.py", line 770, in main
    prnt.loadstyle()
  File "/root/tidos-framework/core/methods/print.py", line 64, in loadstyle
    while thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'

**Comment by VainlyStrain** [comment]
[English]

This issue should have been resolved in the latest commit. To fix it, you can perform the following steps:
1) run `$ git pull` in the TIDoS download directory
2) if TIDoS was installed globally, re-run the installation script

[Français]

Cette erreur a été corrigée dans la dernière révision. Pour appliquer les changements, ces étappes sont nécessaires:
1) exécutez `$ git pull` dans le fichier d'installation initial de TIDoS
2) si vous avez installé TIDoS globalement, vous devez exécuter le programme d'installation encore une fois.

Greetings!

**Comment by 0xInfection** [comment]
I tested this myself, the fix works well. Funny how case toggles affect coding in different languages. ;)

**Comment by VainlyStrain** [comment]
Closing this issue since it has been fixed.
