### ISSUE TITLE
issue executing scan-all module?

### ISSUE THREAD

**Issue by hellresistor** [0xInfection/TIDoS-Framework#122]
Heya! I am here to paste some results. 

On first `^C` i have waited like 2 hours.. and when done the `^C` he continues ;) 

Pay attention on `^C`'s

```
 tid2 > load scan-all
 tid2(scan-all) > info

modules.ScanningEnumeration.scan-all

Launch all scan modules.

Options

+--------------------+
| Name   Desc.   Val |
+--------------------+

 tid2(scan-all) > attack

       /\
      /  \
     /    \   S C A N N I N G   &
    /      \
   /        \   E N U M E R A T I O N
  /          \
 / /\/\  /\/\ \   F I N   S C A N
/ /    \/    \ \
\/            \/

   [Reliable only in LA Networks]

 [§] Enter initial port :> 20
 [§] Enter ending port :> 13000
 [?] Do you want a verbose output? (enter if not) :> y
 [*] Checking port range...
 [!] Port range detected valid...
 [*] Preparing for the the FIN Scan...

^C                     ####################### <<< ------ HERE  ----- >>>
 [+] Target detected online!|
 [*] Beginning scan...
 [!] Scanning initiated at 13:09:02!|

 [*] Sending FIN flagged packet to port : 20
 [*] Sending FIN flagged packet to port : 3265
 [*] Sending FIN flagged packet to port : 6510
 [*] Sending FIN flagged packet to port : 9755
 [*] Receiving incoming packet from port : 3265
 [*] Extracting the received packet...
 [*] Sending FIN flagged packet to port : 3266
 [*] Receiving incoming packet from port : 20
 [*] Extracting the received packet...
 [*] Sending FIN flagged packet to port : 21
 [*] Receiving incoming packet from port : 6510
 [*] Extracting the received packet...
 [*] Sending FIN flagged packet to port : 6511
 [*] Receiving incoming packet from port : 9755
 [*] Extracting the received packet...
 [*] Sending FIN flagged packet to port : 9756
 [*] Receiving incoming packet from port : 3266
 [*] Extracting the received packet...
 [*] Sending FIN flagged packet to port : 3267
 [*] Receiving incoming packet from port : 21
 [*] Extracting the received packet...
 [*] Sending FIN flagged packet to port : 22
 [*] Receiving incoming packet from port : 9756
 [*] Extracting the received packet...
 [*] Sending FIN flagged packet to port : 9757
 [*] Receiving incoming packet from port : 6511
 [*] Extracting the received packet...
 [*] Sending FIN flagged packet to port : 6512
 [*] Receiving incoming packet from port : 9757
 [*] Extracting the received packet...
 [*] Sending FIN flagged packet to port : 9758
 [*] Receiving incoming packet from port : 3267
 [*] Extracting the received packet...
 [*] Sending FIN flagged packet to port : 3268
 [*] Receiving incoming packet from port : 22
 [*] Receiving incoming packet from port : 6512
 [*] Extracting the received packet...
 [*] Extracting the received packet...
 [*] Sending FIN flagged packet to port : 6513
 [*] Sending FIN flagged packet to port : 23
^C [*] Receiving incoming packet from port : 3268
 [*] Extracting the received packet...
 [*] Sending FIN flagged packet to port : 3269
 [*] Receiving incoming packet from port : 6513
 [*] Extracting the received packet...
 [*] Sending FIN flagged packet to port : 6514
 [*] Receiving incoming packet from port : 9758
 [*] Extracting the received packet...
 [*] Sending FIN flagged packet to port : 9759
 [*] Receiving incoming packet from port : 23
 [*] Extracting the received packet...
 [*] Sending FIN flagged packet to port : 24

 [-] User Requested Shutdown...
 [*] Exiting...
 tid2(scan-all) > Traceback (most recent call last):
  File "tidconsole.py", line 782, in <module>
    main()
  File "tidconsole.py", line 777, in main
    TIDcon().cmdloop()
  File "tidconsole.py", line 52, in cmdloop
    super(TIDcon, self).cmdloop(intro=None)
  File "/usr/lib/python3.6/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.
$
```

**Comment by VainlyStrain** [comment]
Hi! There was an issue that KeyboardInterrupts got handled smoothly as Exceptions. I have uploaded a fix for it. Could you confirm it works for scan-all?

Greetings!

**Comment by VainlyStrain** [comment]
Closing this issue since it has been fixed. If problems reoccur, contact me again.
