### ISSUE TITLE
plz help i cannot run it on kali linux it shows this error ?

### ISSUE THREAD

**Issue by gr3ncode** [0xInfection/TIDoS-Framework#126]
it dosent work on kali linux plz help

┌──(root💀kali)-[~]
└─# tidos
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 13, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 31, in <module>
    from core.Auxillaries.auxil import *
  File "/opt/tidos/core/Auxillaries/auxil.py", line 23, in <module>
    from imgext import *
  File "modules/0x05-Auxillaries+PF6/imgext.py", line 13, in <module>
    import PIL.ExifTags
ImportError: No module named PIL.ExifTags

**Comment by 0xInfection** [comment]
When you face a problem, the first thing that should come to your mind is to google it.
