### ISSUE TITLE
Error Msg - ImportError: libmysqlclient.so.18: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by filebe777** [0xInfection/TIDoS-Framework#50]
```
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 37, in <module>
    from core.Vulnlysis.vuln import *
  File "/opt/tidos/core/Vulnlysis/vuln.py", line 17, in <module>
    from core.Vulnlysis.Oth_Bugs.othbugs import *
  File "/opt/tidos/core/Vulnlysis/Oth_Bugs/othbugs.py", line 22, in <module>
    from sqlbrute import *
  File "modules/0x03-Vulnerability+Analysis/0x03-OtherWebBugs/sqlbrute.py", line 12, in <module>
    import _mysql
ImportError: libmysqlclient.so.18: cannot open shared object file: No such file or directory
```

**Comment by 0xInfection** [comment]
Did you follow the installation errors properly? Are you running this on Python 2?

**Comment by filebe777** [comment]
i fixed it, found something on google.

pip uninstall MySQL-python
pip install MySQL-python

works fine now
