### ISSUE TITLE
tidos is not running

### ISSUE THREAD

**Issue by gbiagomba** [0xInfection/TIDoS-Framework#52]
Hello @0xInfection ,

I performed a clean install of TIDoS and now I am having issues running the tidos script. Below is the output of my first run
```
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 36, in <module>
    from core.Enumeration.scanenum import *
  File "/opt/tidos/core/Enumeration/scanenum.py", line 24, in <module>
    from ssltlsscan import *
  File "modules/0x02-Scanning+Enumeration/ssltlsscan.py", line 15, in <module>
    import sslyze
ImportError: No module named sslyze
```

**Comment by 0xInfection** [comment]
Follow the steps [here](https://github.com/0xInfection/TIDoS-Framework/issues/28). It should solve your error.

**Comment by gbiagomba** [comment]
@0xInfection I reran the install and it seemed to have installed correctly

**Comment by 0xInfection** [comment]
@gbiagomba good to see you up and running.
