### ISSUE TITLE
tidos is not running

### ISSUE THREAD

**Issue by avishkak** [0xInfection/TIDoS-Framework#53]
```
[root@localhost tidos-framework]# tidos
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 32, in <module>
    from core.Auxillaries.auxil import *
  File "/opt/tidos/core/Auxillaries/auxil.py", line 23, in <module>
    from imgext import *
  File "modules/0x05-Auxillaries+PF6/imgext.py", line 17, in <module>
    from pyexiv2 import ImageMetadata, ExifTag # python2
  File "/usr/lib64/python2.7/site-packages/pyexiv2-0.3.2-py2.7-linux-x86_64.egg/pyexiv2/__init__.py", line 60, in <module>
    import libexiv2python
ImportError: libboost_python-py27.so.1.62.0: cannot open shared object file: No such file or directory
```

**Comment by avishkak** [comment]
Im running this on Fedora 29

**Comment by 0xInfection** [comment]
Before submitting any issue, try Googling the error for at least once. Here's what I got on [StackOverflow](https://stackoverflow.com/questions/13578174/pyexiv2-import-error-libexiv2-so-12-not-found).

**Comment by 0xInfection** [comment]
This is for a note that `pyexiv2` is no more a dependency for TIDoS, so neither is `Boost Python`, so now TIDoS should work fine without them and should not throw out this error.
