### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by jojo6r57346** [0xInfection/TIDoS-Framework#54]
Doesn't work. Actually the same problem as the previous user has. Previous version worked. Using ParrotOS.
P.S. Why python2.7? Shodan doesn't work correctly or smth like that?
Dude, you have a perfect project, may be subsitute for recon-ng. Debug your product. Thanks a lot, man.

**Comment by 0xInfection** [comment]
Can you at least tell me what is the problem you're facing?

**Comment by jojo6r57346** [comment]
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 37, in <module>
    from core.Vulnlysis.vuln import *
  File "/opt/tidos/core/Vulnlysis/vuln.py", line 18, in <module>
    from core.Vulnlysis.Serio_Bugs.serbugs import *
  File "/opt/tidos/core/Vulnlysis/Serio_Bugs/serbugs.py", line 23, in <module>
    from csrf import *
  File "modules/0x03-Vulnerability+Analysis/0x01-TopPriorityBugs/csrf.py", line 18, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup

**Comment by 0xInfection** [comment]
I am not going to give you the solution, google it.

**Comment by sumgro** [comment]
I've been facing the same error and have tried google to find a solution, but in vain.

Request you to support with possible solution. 

Thanks
