### ISSUE TITLE
No module named PIL.ExifTags

### ISSUE THREAD

**Issue by godeyes333** [0xInfection/TIDoS-Framework#57]
```python2 tidos.py```
```
Traceback (most recent call last):                                                                  File "tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/root/tidos-framework/core/tidos_main.py", line 32, in <module>
    from core.Auxillaries.auxil import *                                                            File "/root/tidos-framework/core/Auxillaries/auxil.py", line 23, in <module>                        from imgext import *
  File "modules/0x05-Auxillaries+PF6/imgext.py", line 14, in <module>                                 import PIL.ExifTags
ImportError: No module named PIL.ExifTags
```

**Comment by 0xInfection** [comment]
You should do a basic googling before submitting any issues regarding local dependency errors. A `pip install pillow` will fix it.

**Comment by 0xInfection** [comment]
You should do a basic googling before submitting any issues regarding local dependency errors. A `pip install pillow` will fix it.
