### ISSUE TITLE
libmariadbclient18 issues after clean install

### ISSUE THREAD

**Issue by Nigrini** [0xInfection/TIDoS-Framework#68]
1. Fresh install of Kali Linux 2019.1
2. Sources.list entries = 
    deb http://http.kali.org/kali kali-rolling main non-free contrib
    deb-src http://http.kali.org/kali kali-rolling main non-free contrib
3. Update and Upgrade completed
4. git clone https://github.com/0xInfection/TIDoS-Framework.git
5. cd tidos-framework
    chmod +x install
    ./install
6. pip install -r requirements.txt

As you can see - Nothing fancy, just a normal installation on a clean system.

**When trying to run the program:**

```
root@Xero:~/TIDoS-Framework# tidos
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 37, in <module>
    from core.Vulnlysis.vuln import *
  File "/opt/tidos/core/Vulnlysis/vuln.py", line 17, in <module>
    from core.Vulnlysis.Oth_Bugs.othbugs import *
  File "/opt/tidos/core/Vulnlysis/Oth_Bugs/othbugs.py", line 22, in <module>
    from sqlbrute import *
  File "modules/0x03-Vulnerability+Analysis/0x03-OtherWebBugs/sqlbrute.py", line 12, in <module>
    import _mysql
  File "build/bdist.linux-x86_64/egg/_mysql.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/_mysql.py", line 6, in __bootstrap__
ImportError: libmariadbclient.so.18: cannot open shared object file: No such file or directory
```
**Trying to install libmariadbclient18**
```
root@Xero:~/TIDoS-Framework#  apt-get install libmariadbclient18
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libmariadbclient18 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
**However the following packages replace it:
  libmariadb3**

E: Package 'libmariadbclient18' has no installation candidate
```

**Comment by 0xInfection** [comment]
Okay so I saw everyone was facing this issue on latest distros. It was actually due to a deprecated library function which I was using in my code. This error should be fixed in 03a8e17.
