### ISSUE TITLE
sslyze cannot install

### ISSUE THREAD

**Issue by jepunband** [0xInfection/TIDoS-Framework#89]
Hi failing to install ... pip install don't work & I tried the solution at #28 still the same.

Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 13, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 35, in <module>
    from core.Enumeration.scanenum import *
  File "/opt/tidos/core/Enumeration/scanenum.py", line 25, in <module>
    from ssltlsscan import *
  File "modules/0x02-Scanning+Enumeration/ssltlsscan.py", line 14, in <module>
    import sslyze
ImportError: No module named sslyze

I think Sslyze not availabe for armv7 device. Anyone has it running on nethunter?

**Comment by 0xInfection** [comment]
You might be able to use Dockerfile to get TIDoS installed properly. :)
