### ISSUE TITLE
 No module named xmpp

### ISSUE THREAD

**Issue by autoruntesting** [0xInfection/TIDoS-Framework#90]
1.sna@Sis:~/TIDoS-Framework# tidos 
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 37, in <module>
    from core.Vulnlysis.vuln import *
  File "/opt/tidos/core/Vulnlysis/vuln.py", line 17, in <module>
    from core.Vulnlysis.Oth_Bugs.othbugs import *
  File "/opt/tidos/core/Vulnlysis/Oth_Bugs/othbugs.py", line 25, in <module>
    from xmppbrute import *
  File "modules/0x03-Vulnerability+Analysis/0x03-OtherWebBugs/xmppbrute.py", line 18, in <module>
    from xmpp import Client
ImportError: No module named xmpp

2. :~/TIDoS-Framework# sudo apt-get install -y python-xmpp
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-xmpp

3.This my error how to fix it ?

**Comment by johntyty912** [comment]
try this:
```
git clone https://github.com/normanr/xmpppy.git
cd xmpppy
python setup.py install
```

**Comment by autoruntesting** [comment]
thanks
