### ISSUE TITLE
cant launch tidos

### ISSUE THREAD

**Issue by DestinyofYeet** [0xInfection/TIDoS-Framework#91]
when im typing in "sudo tidos" or go in the directory and run "sudo python2 tidos.py" i get this error message:

Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 37, in <module>
    from core.Vulnlysis.vuln import *
  File "/opt/tidos/core/Vulnlysis/vuln.py", line 17, in <module>
    from core.Vulnlysis.Oth_Bugs.othbugs import *
  File "/opt/tidos/core/Vulnlysis/Oth_Bugs/othbugs.py", line 22, in <module>
    from sqlbrute import *
  File "modules/0x03-Vulnerability+Analysis/0x03-OtherWebBugs/sqlbrute.py", line 15, in <module>
    import mysql.connector as mysql
ImportError: No module named mysql.connector

**Comment by DestinyofYeet** [comment]
found my solution :

pip install mysql-connector-python
