### ISSUE TITLE
ImportError - xmpp

### ISSUE THREAD

**Issue by sineyed** [0xInfection/TIDoS-Framework#96]
I am having trouble doing both manual and global installations. I get the same error. Could you please assist?

Traceback (most recent call last):
  File "tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/opt/test/TIDoS-Framework/core/tidos_main.py", line 37, in <module>
    from core.Vulnlysis.vuln import *
  File "/opt/test/TIDoS-Framework/core/Vulnlysis/vuln.py", line 17, in <module>
    from core.Vulnlysis.Oth_Bugs.othbugs import *
  File "/opt/test/TIDoS-Framework/core/Vulnlysis/Oth_Bugs/othbugs.py", line 25, in <module>
    from xmppbrute import *
  File "modules/0x03-Vulnerability+Analysis/0x03-OtherWebBugs/xmppbrute.py", line 18, in <module>
    from xmpp import Client
ImportError: No module named xmpp

**Comment by ll3N1GmAll** [comment]
I am having this same error on Kali

**Comment by D4rk3rkali** [comment]
try it now i ran the same commands u did and it worked

**Comment by D4rk3rkali** [comment]
> I am having this same error on Kali. Tried - pip install xmpp and pip3 install xmpp.
> Just ran these:
> pip install xmpppy
> AND
> pip3 install xmpppy
> AND
> pip install pyxmpp2
> Still getting the same error.

try it now i ran the same commands u did and it worked

**Comment by superdeen** [comment]
I get this same error at my end, I ran pip install xmpppy. It returned 
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xmpppy in /home/coolcat/.local/lib/python2.7/site-packages (0.6.1)

I tried sudo tidos after this but I got same error as earlier on
 Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 37, in <module>
    from core.Vulnlysis.vuln import *
  File "/opt/tidos/core/Vulnlysis/vuln.py", line 17, in <module>
    from core.Vulnlysis.Oth_Bugs.othbugs import *
  File "/opt/tidos/core/Vulnlysis/Oth_Bugs/othbugs.py", line 25, in <module>
    from xmppbrute import *
  File "modules/0x03-Vulnerability+Analysis/0x03-OtherWebBugs/xmppbrute.py", line 18, in <module>
    from xmpp import Client
ImportError: No module named xmpp
